package uk.co.r99companion

/**
 * The capability bitmap returned by GetDeviceSupportFunction, decoded exactly as the vendor
 * SDK does it in DataUnpack.saveDeviceSupportFunctionData: one flag per bit, most significant
 * bit first. Extracted rather than guessed; see PROTOCOL.md.
 */
data class Capability(val index: Int, val bit: Int, val label: String)

val CAPABILITIES = listOf(
    Capability(0, 7, "Step Count"),
    Capability(0, 6, "Sleep"),
    Capability(0, 5, "Real Data"),
    Capability(0, 4, "Firmware Update"),
    Capability(0, 3, "Heart Rate"),
    Capability(0, 2, "Information"),
    Capability(0, 1, "Many Language"),
    Capability(0, 0, "Blood"),
    Capability(1, 7, "Heart Alarm"),
    Capability(1, 6, "Blood Alarm"),
    Capability(1, 5, "Ecg Real Upload"),
    Capability(1, 4, "Ecg History Upload"),
    Capability(1, 3, "Blood Oxygen"),
    Capability(1, 2, "Respiratory Rate"),
    Capability(1, 1, "Hrv"),
    Capability(1, 0, "More Sport"),
    Capability(2, 0, "Alarm Count"),
    Capability(3, 7, "Custom"),
    Capability(3, 6, "Meeting"),
    Capability(3, 5, "Party"),
    Capability(3, 4, "Appoint"),
    Capability(3, 3, "Take Pills"),
    Capability(3, 2, "Take Exercise"),
    Capability(3, 1, "Take Sleep"),
    Capability(3, 0, "Get Up"),
    Capability(4, 7, "Call Phone"),
    Capability(4, 6, "Message"),
    Capability(4, 5, "Email"),
    Capability(4, 4, "QQ"),
    Capability(4, 3, "We Chat"),
    Capability(4, 2, "Sina"),
    Capability(4, 1, "Face Book"),
    Capability(4, 0, "Twitter"),
    Capability(5, 7, "Whats APP"),
    Capability(5, 6, "Messenger"),
    Capability(5, 5, "Instagram"),
    Capability(5, 4, "Linked In"),
    Capability(5, 3, "Line"),
    Capability(5, 2, "Snap Chat"),
    Capability(5, 1, "Skype"),
    Capability(5, 0, "Other Messenger"),
    Capability(6, 7, "Long Sitting"),
    Capability(6, 6, "Anti Lost"),
    Capability(6, 5, "Find Phone"),
    Capability(6, 4, "Find Device"),
    Capability(6, 3, "Factory Setting"),
    Capability(6, 2, "Blood Level"),
    Capability(6, 1, "Noti Toggle"),
    Capability(6, 0, "Lift Bright"),
    Capability(7, 7, "Skin Color"),
    Capability(7, 6, "We Chat Sport"),
    Capability(7, 5, "Search Around"),
    Capability(7, 4, "Today Weather"),
    Capability(7, 3, "Tomorrow Weather"),
    Capability(7, 2, "ECGDiagnosis"),
    Capability(7, 1, "Phone Support"),
    Capability(7, 0, "Encryption"),
    Capability(8, 7, "Temp Alarm"),
    Capability(8, 6, "Temp Axillary Test"),
    Capability(8, 5, "CVRR"),
    Capability(8, 4, "Blood Pressure Calibration"),
    Capability(8, 3, "ECGRight Electrode"),
    Capability(8, 2, "Theme"),
    Capability(8, 1, "Music"),
    Capability(8, 0, "Temp"),
    Capability(9, 7, "Inaccurate ECG"),
    Capability(9, 6, "Contacts"),
    Capability(9, 5, "Dial"),
    Capability(9, 4, "Female Physiological Cycle"),
    Capability(9, 3, "Shake Take Photo"),
    Capability(9, 2, "Manual Take Photo"),
    Capability(9, 1, "Set Info"),
    Capability(9, 0, "Temp Calibration"),
    Capability(10, 7, "Realtime Monitoring Mode"),
    Capability(10, 6, "Indoor Walking"),
    Capability(10, 5, "Outdoor Walking"),
    Capability(10, 4, "Indoor Runing"),
    Capability(10, 3, "Outdoor Runing"),
    Capability(10, 2, "Ping Pong"),
    Capability(10, 1, "Foot Ball"),
    Capability(10, 0, "Mountain Climbing"),
    Capability(11, 7, "Running"),
    Capability(11, 6, "Fitness"),
    Capability(11, 5, "Riding"),
    Capability(11, 4, "Rope Skipping"),
    Capability(11, 3, "Basketball"),
    Capability(11, 2, "Swimming"),
    Capability(11, 1, "Walking"),
    Capability(11, 0, "Badminton"),
    Capability(14, 7, "On Foot"),
    Capability(14, 6, "Yoga"),
    Capability(14, 5, "Weight Training"),
    Capability(14, 4, "Jumping"),
    Capability(14, 3, "Sit Ups"),
    Capability(14, 2, "Rowing Machine"),
    Capability(14, 1, "Stepper"),
    Capability(14, 0, "Indoor Riding"),
    Capability(15, 0, "Real Exercise Data"),
    Capability(15, 1, "Test Heart"),
    Capability(15, 2, "Test Blood"),
    Capability(15, 3, "Test Spo2"),
    Capability(15, 4, "Test Temp"),
    Capability(15, 5, "Test Respiration Rate"),
    Capability(15, 6, "Kinds Information Push"),
    Capability(15, 7, "Custom Dial"),
    Capability(16, 0, "Inflated"),
    Capability(16, 1, "Sos"),
    Capability(16, 2, "Blood Oxygen Alarm"),
    Capability(16, 3, "Upload Inflate Blood"),
    Capability(16, 4, "Viber Notify"),
    Capability(16, 5, "Other Notify"),
    Capability(16, 6, "Is Flip Dial Image"),
    Capability(17, 0, "Vibration Intensity"),
    Capability(17, 1, "Set Screen Time"),
    Capability(17, 2, "Watch Screen Brightness"),
    Capability(17, 3, "Blood Sugar"),
    Capability(17, 4, "Pause Exercise"),
    Capability(17, 5, "Drink Water Reminder"),
    Capability(17, 6, "Business Card"),
    Capability(17, 7, "Uric Acid Measurement"),
    Capability(18, 0, "Volleyball"),
    Capability(18, 1, "Kayak"),
    Capability(18, 2, "Roller Skating"),
    Capability(18, 3, "Tennis"),
    Capability(18, 4, "Golf"),
    Capability(18, 5, "Elliptical Machine"),
    Capability(18, 6, "Dance"),
    Capability(18, 7, "Rock Climbing"),
    Capability(19, 0, "Aerobics"),
    Capability(19, 1, "Other Sports"),
    Capability(20, 0, "Blood Ketone Measurement"),
    Capability(20, 1, "ALi IOT"),
    Capability(20, 2, "Create Bond"),
    Capability(20, 3, "Respiratory Rate Alarm"),
    Capability(20, 4, "Imprecise Blood Fat"),
    Capability(20, 5, "Independent Automatic Time Measurement"),
    Capability(20, 6, "Recording File"),
    Capability(20, 7, "Physiotherapy"),
    Capability(21, 0, "Zoom Notify"),
    Capability(21, 1, "Tik Tok Notify"),
    Capability(21, 2, "Kakao Talk Notify"),
    Capability(22, 0, "Sleep Remind"),
    Capability(22, 1, "Device Spec"),
    Capability(22, 2, "Local Sport Data"),
    Capability(22, 3, "LOGO"),
    Capability(22, 4, "Is Motion Delay Disconnect"),
    Capability(22, 5, "Battery Info Upload"),
    Capability(22, 6, "Pressure"),
    Capability(22, 7, "Maximal Oxygen Intake"),
    Capability(23, 0, "Hrv Measurement"),
    Capability(23, 1, "Blood Sugar Measurement"),
    Capability(23, 2, "Pressure Measurement"),
    Capability(23, 3, "Oxygenintake Measurement"),
    Capability(23, 4, "Blood Fat Measurement"),
    Capability(23, 5, "Is App Has Uric Acid Measurement"),
    Capability(23, 6, "Is App Has Start Prayer"),
    Capability(24, 0, "Precision Blood Glucose"),
    Capability(24, 1, "Precision Lipids"),
    Capability(24, 2, "Precision Uric Acid"),
    Capability(24, 3, "Precision Blood Ketone"),
    Capability(25, 0, "Sporadic Naps"),
    Capability(25, 1, "IS  HAS  Measurement Function"),
    Capability(25, 2, "Is has location data feature"),
    Capability(25, 3, "IS  HAS  Algorithmic License"),
    Capability(25, 4, "Sedentary Report"),
    Capability(25, 5, "Heng Ai Blood Pressure"),
    Capability(25, 6, "Heng Ai Emotion Pressure"),
    Capability(25, 7, "IS  HAS  MF  BLOOD  OXYGEN"),
    Capability(26, 0, "IS  HAS  MF  BLOOD  PRESSURE"),
    Capability(26, 1, "IS  HAS  MF  HEART  RATE"),
    Capability(26, 2, "IS  HAS  MF  BLOOD  PRESSURE  ACCURATE"),
    Capability(26, 3, "IS  HAS  MF  ECG"),
    Capability(26, 4, "IS  HAS  MF  HRV"),
    Capability(26, 5, "IS  HAS  MF  TEMPERATURE"),
)
